### PR TITLE
Initial ruby support.

### PR DESCRIPTION
**Pull request by Eric-Guo**

### CODE REVIEW

**Comment by ctf0** [comment]
could u also add a screen shot for it and update the readme ?

**Comment by Eric-Guo** [comment]
with pressure :smile:

**Comment by ctf0** [comment]
LOL, thanx :metal:

**Comment by Eric-Guo** [comment]
I think below code is pretty good as almost all element is include.

Thanks your effort to adjust the right color.
```ruby
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :set_current_user

  def render_404
    render_optional_error_file(404)
  end

  def render_optional_error_file(status_code)
    status = status_code.to_s
    fname = %w(404 403 422 500).include?(status) ? status : 'unknown'
    render template: "/errors/#{fname}", format: [:html],
           handler: [:erb], status: status, layout: 'application'
  end

  rescue_from ActionController::InvalidAuthenticityToken do |_exception|
    redirect_to new_user_session_path, alert: '请先登录。'
  end

  private

  def set_current_user
    User.current_user = current_user
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:password, :password_confirmation, :current_password, :name)
    end
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:name, :email, :password, :remember_me)
    end
  end
end
```

**Comment by ctf0** [comment]
thanx :)

**Pull request merged**
