### PR TITLE
Palette reduction. Removed color duplicates.

### PR DESCRIPTION
**Pull request by pykong**
Further reduced palette down to just **65** colors.
The current color palette includes several colors that can just not be told apart.
Let's call them `color dupes` for the lack of a formal term.

We should strive to eliminate those `color dupes` to give the user a cleaner experience and also keep to DRY principles.

We may also use the newly gained space to carefully introduce new colors if it makes sense and enriches user experience.

@ctf0 And kudos for single handed removing colors from almost `200` down to `85`. This alone is a great step forward.

Successor of: #35
Fixes: #34

### CODE REVIEW

**Comment by ctf0** [comment]
@pykong if the palette count is within a reasonable number, do we still need this PR ?

**Comment by pykong** [comment]
@ctf0 This is not about absolute number, as I have pointed out.
But about eliminating color duplicates to create a consistent color palette.
Many colors in the current palette look identical.

So, yes IMHO this PR is necessary because it is a step forward to a defined color palette.
This will facilitate development. I.E. once we got such defined color palette any changes or additions
to the theme can be informed by it. We will only choose colors from that palette and thereby guarantee that the theme stays consistent throughout any changes made.

**Comment by ctf0** [comment]
okay, can u give me an absolute number of the current count in master and if possible can u also add the palette ?

**Comment by pykong** [comment]
Yes. I am going to later the day.

**Comment by pykong** [comment]
- The number were previously close to `200`!
- You did an awesome job at bringing that count down to `85`.
- I have eliminated 20 very similar looking colors with your neat little tool, hence the this PR will bring colors down to `65`.

Palette is attached:
[colors-vis-List.txt](https://github.com/ctf0/Seti_UX/files/1808272/colors-vis-List.txt)

**Comment by ctf0** [comment]
awesome work, i'll test ur changes today and will marge after

**Comment by pykong** [comment]
You are awesome! who else would have made the best color scheme for ST? ;-)

**Comment by ctf0** [comment]
btw i think the colors with alpha shouldn't be counted for aka.**colors with 8 characters**

**Comment by ctf0** [comment]
i've cleaned up some and now they are **77** out of **84**, excluding the colors with alpha

[colors-vis-List (1).txt](https://github.com/ctf0/Seti_UX/files/1808888/colors-vis-List.1.txt)

i've updated the scheme with the changes, ignore the conflict for now, give it a shot and tell me what u think.

**Comment by pykong** [comment]
You are the designer, I am a mere coder.
Could you help me understand why we would need the alpha channel (`A`), if it does not help me discern two colors with the same `RGB`? I think I have rather accurate vision and a reasonable color true display, but many colors albeit differing in value are not discernible for me.

I have pushed a super minimal version of the theme with a mere 50 colors.
Thoroughly eliminating any color duplicates I could spot.

What about starting from those 50 colors and then carefully add new colors in a sensible manner?
This bottom-up approach can lead to a cleaner palette.

**Comment by ctf0** [comment]
the tool on codepen doesnt show the alpha correctly, but in ST the alpha simply create a subtle difference of the original color.

**Comment by pykong** [comment]
Ah OK. Let's stick with your 77 then!

**Pull request closed without merging**
