### PR TITLE
Added Advanced Python Language Definitions

### PR DESCRIPTION
**Pull request by pyking2**
Support Peter Varo's Python 3 and MattDMo's Python Improved language definitions.
Both are highly popular on SublimeText.
Definitions are taken from the Gloom and Neon color schemes associated with those packages - scopes already in use.
Colors have remained the same for now and can be adjusted at a later point in time if required.

### CODE REVIEW

**Comment by ctf0** [comment]
thanx for the update but small note about colors

i think what drives users to choose a HL scheme over another is the coloring, so if you installed a package that doesnt have consistency in coloring you will simply hate it.

i believe that having scope support with bad colors is worse than not having support at all.

so what u think ?

**Comment by bfelder** [comment]
The coloring is already pretty consistent across different python packages.
Interestingly the packages affect only minor scopes, as they're an addition to Sublime's inbuilt definition, not a complete rewrite like MagicPython.

Obviously, code could not look identical across all language definitions as the scopes catch different keywords and contexts. What we can strive for is to still make it always look like Seti_UX, though. ;-)
That is what I mean with consistent.

I will have another look at it to get it even better.

BTW - What do you think of merging the sections of Python, MagicPython and the other two?
The end result would be more maintainable. Scopes affecting same keywords could be put under the same XML node.

I so far shrunk away from this, as I saw benefit in keeping them separate.
But now I seriously consider this possibility.

**Comment by ctf0** [comment]
again u r the expert with python here, and i prefer to leave it to u.

if you want to add more support for python, yes go for it, do all u want.

my only issue is coloring, try to keep it as close to the ones that already comes with seti instead of adding colors from other schemes that will look bad with seti

if you need more colors use the below as ref

json

**Comment by bfelder** [comment]
@ctf0 Great to have this color palette. It would be better though if it included the actual color values in hex.

**Comment by ctf0** [comment]
@bfelder https://github.com/ctf0/Seti_UX/commit/0f83b7abf87e724e6e569fb47285e0eef20db96b

**Comment by bfelder** [comment]
@ctf0 I have decided to risk merging the xml nodes. I do not expect the syntax definitions to evolve much more and only by that way will the scheme be maintainable (otherwise you will have to edit up to four places to change the color of a single keyword)

This will take much more time though. Expect me to come back at the end of the month.

P.S.: Did you join [Sublime Text on discord](https://discordapp.com/invite/D43Pecu)? It is a great place to exchange about all topics regarding Sublime plugin development.

**Comment by ctf0** [comment]
np, take ur time.

and no i didnt, but isnt thats what the forum is for ?

**Comment by pyking2** [comment]
done

**Pull request merged**
