### PR TITLE
Added python definitions from Neon.tmTheme

### PR DESCRIPTION
**Pull request by pykong**
Neon.tmTheme is the color scheme belonging to the Python Improved language plugin.
I have inserted its python definitions into Seti.tmTheme.
A check for duplicate scopes I ran against the modified file did not find any *additional* duplications.

#### TODO:
- adapt colors

### CODE REVIEW

**Comment by ctf0** [comment]
r u sure you don't need to change anything else about python ? if yes, then fix the conflict so we can merge it

**Comment by pykong** [comment]
Sorry. Busy as you are. It is on my TODO list.

**Comment by pykong** [comment]
With the recent improvement of the default python syntax highlighting, python extensions provide not sufficient value anymore to justify the effort to include them into color scheme, IMHO.

**Comment by ctf0** [comment]
okey, i've also removed magic python def from the scheme

**Pull request closed without merging**
